server:
  port: 10086 # 服务端口
spring:
  application:
    name: eurekaserver # eureka的服务名称
eureka:
  instance:
    prefer-ip-address: true
    # 心跳间隔
    lease-renewal-interval-in-seconds: 2
    #没有心跳的淘汰时间
    lease-expiration-duration-in-seconds: 4
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false #自身 不在向eureka注册
    fetch-registry: false  #启动时禁用client的注册
    #registry-fetch-interval-seconds: 1

  server:
    # 禁用一级缓存
    use-read-only-response-cache: false
    # 自我保护模式
    enable-self-preservation: false
    # 主动失效间隔
    eviction-interval-timer-in-ms: 1000
    # 没有心跳的淘汰时间





