spring:
  application:
#    name: Python-user-sidecar
    name: user-sidecar
server: #自己
  port: 8061
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka

    # 定期刷新本地缓存的时间
    registry-fetch-interval-seconds: 3

  instance:
    prefer-ip-address: true
    instance-id: Python-user-sidecar
    # 心跳间隔，5秒
    lease-renewal-interval-in-seconds: 2
    # 无心跳淘汰时间 10秒
    lease-expiration-duration-in-seconds: 4




sidecar:
  port: 8091 #监听对象
  health-uri: http://localhost:${sidecar.port}/health
