spring:
  application:
    name: Controller

server: #自己
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:10086/eureka
    fetch-registry: true
    #  注册表更新时间
    registry-fetch-interval-seconds: 3
    #disable-delta: true

  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 6





