server:
  port: 8081

spring:
  thymeleaf:
    prefix: classpath:/templates/fzy_demo/
    suffix: html

  datasource:
    #url: jdbc:mysql://localhost:3306/clouduser?useSSL=false
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: userservice
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
    # 更新本地缓存的时间
    registry-fetch-interval-seconds: 3
  instance:
    instance-id: Java-user-service
    lease-expiration-duration-in-seconds: 6
    lease-renewal-interval-in-seconds: 3

#    register-with-eureka: false #自身 不在向eureka注册
#   fetch-registry: false  #启动时禁用client的注册