server:
  port: 8080

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/tborder?useSSL=false
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: orderservice
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

eureka:
  client:
    service-url:  # eureka的地址信息
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: Java-order-service
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10



#      ip-address: ${ipAddress:127.0.0.1}
#      prefer-ip-address: true
#    register-with-eureka: false #自身 不在向eureka注册
#    fetch-registry: false  #启动时禁用client的注册

#   zuul:
#  routes:
#    sideuser:
#      path: /order/**
#      service-id: order-sidecar